---
version: '3'

services:
  db:
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_USER: wordpress
      MYSQL_DATABASE: wordpress
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
  wordpress:
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    depends_on:
      - db
    image: wordpress
    ports:
      - 3070:80
    restart: always
    volumes:
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/mu-plugins/bootstrap-hooks
      - ./bin/install-wp.sh:/usr/local/bin/install-wp
      - .uploads:/var/www/html/wp-content/uploads
      - .plugins:/var/www/html/wp-content/plugins
      - ./test/fixtures/themes/bootstrap-hooks:/var/www/html/wp-content/themes/bootstrap-hooks
      - ./test/fixtures/themes/bootstrap-blocks:/var/www/html/wp-content/themes/bootstrap-blocks
      - ./test/fixtures/themes/bootstrap-twentyseventeen:/var/www/html/wp-content/themes/bootstrap-twentyseventeen
      - ./test/fixtures/themes/bootstrap-twentytwentytwo:/var/www/html/wp-content/themes/bootstrap-twentytwentytwo
    working_dir: /var/www/html
  wp:
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    image: wordpress:cli
    user: '33:33'
    depends_on:
      - db
      - wordpress
    volumes:
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/mu-plugins/bootstrap-hooks
      - ./bin/install-wp.sh:/usr/local/bin/install-wp
      - .uploads:/var/www/html/wp-content/uploads
      - .plugins:/var/www/html/wp-content/plugins
    links:
      - db:db
    command: "--info"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 3071:80
    volumes:
      - /sessions
  composer:
    image: composer
    command: install
    working_dir: /var/www/html
    depends_on:
      - wordpress
    volumes:
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
      - ./bin/install-wp.sh:/usr/local/bin/install-wp
      - .uploads:/var/www/html/wp-content/uploads
      - .plugins:/var/www/html/wp-content/plugins
      - wordpress:/var/www/html
    links:
      - wordpress:wordpress
volumes:
  db_data:
  wordpress:
